openapi: 3.1.0
info:
  title: Scavini Product API
  description: API para consultar productos textiles (cintas trenzadas).
  version: 1.0.0
servers:
  - url: https://scavini-product-api-bvbybfcncpcbh9hx.westeurope-01.azurewebsites.net
paths:
  /productos:
    get:
      summary: Obtener todos los productos.
      operationId: obtenerProductos
      responses:
        '200':
          description: Lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    tipo_tejido:
                      type: string
                    precio_por_metro:
                      type: number
                    colores:
                      type: array
                      items:
                        type: string
  /productos/{producto_id}:
    get:
      summary: Obtener detalles de un producto por ID.
      operationId: obtenerProductoPorId
      parameters:
        - name: producto_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del producto.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  tipo_tejido:
                    type: string
                  precio_por_metro:
                    type: number
                  colores:
                    type: array
                    items:
                      type: string
  /tipos:
    get:
      summary: Obtener todos los tipos de tejidos.
      operationId: obtenerTipos
      responses:
        '200':
          description: Lista de tipos de tejidos.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
  /colores:
    get:
      summary: Obtener todos los colores disponibles.
      operationId: obtenerColores
      responses:
        '200':
          description: Lista de colores.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    color:
                      type: string
                    producto_nombre:
                      type: string
